services:
  front:
    build:
      context: ../2109-wns-paris-les-semicroustillant-front
      dockerfile: Dockerfile-prod
    ports:
      - 8080:3000
    # depends_on:
    #   back:
    #     condition: service_healthy
    volumes:
      - ../2109-wns-paris-les-semicroustillant-front/src:/app/src
  back:
    build:
      context: ./
      dockerfile: Dockerfile-prod
    ports:
      - 5050:4000
    # healthcheck:
    #   test: ['CMD-SHELL', 'curl -f http://localhost:5050 || exit 1']
    #   timeout: 10s
    #   interval: 10s
    #   retries: 10
    volumes:
      - ./src/:/app/src
  mongodb:
    image: mongo
    volumes:
      - ./data:/data/db

# must target Dockerfile-prod