services:
  front:
    build: ../2109-wns-paris-les-semicroustillant-front
    ports:
      - 8080:3000
    volumes:
      - ../2109-wns-paris-les-semicroustillant-front/src:/app/src
  back:
    build: ./
    ports:
      - 5050:5000
    command: npm run dev
    volumes:
      - ./src/:/app/src
  mongodb:
    image: mongo
    volumes:
      - ./data:/data/db