services:
  server:
    image: semiwcs/2109-wns-paris-les-semicroustillant-back:latest
    command: sh -c "npm run start:prod"
    ports:
      - 5050:4000
    depends_on:
      - mongodb

    ## @TODO: Healtcheck prevents the container from starting with Docker
    ## MUST BE FIXED
    # healthcheck:
    #   test: ['CMD-SHELL', 'curl -f http://localhost:5050 || exit 1']
    #   timeout: 10s
    #   interval: 10s
    #   retries: 10
    volumes:
      - ./src/:/app/src
  front:
    image: semiwcs/2109-wns-paris-les-semicroustillant-front:latest
    command: sh -c "npm run build"
    ports:
      - 8080:3000

    ## @TODO: Healtcheck issue
    ## MUST BE FIXED
    # depends_on:
    #   back:
    #     condition: service_healthy
    volumes:
      - front-build:/app/build
    depends_on:
      - server

  mongodb:
    image: mongo:5.0
    volumes:
      - ./data:/data/db
  nginx:
    image: nginx:1.21.3
    depends_on:
      - front
      - server
    restart: always
    ports:
      - ${GATEWAY_PORT:-8000}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - front-build:/front-build
      - ./logs:/var/log/nginx

volumes:
  front-build:
