services:
  front:
    image: semiwcs/2109-wns-paris-les-semicroustillant-front:latest
    command: sh -c "npm run build"

    ## @TODO: Healtcheck issue
    ## MUST BE FIXED
    # depends_on:
    #   back:
    #     condition: service_healthy
    volumes:
      - ../2109-wns-paris-les-semicroustillant-front/src:/app/src
  back:
    image: semiwcs/2109-wns-paris-les-semicroustillant-back:latest
    command: sh -c "npm run build && npm run prod"
    expose:
      - 4000
    depends_on:
      - mongodb

    ## @TODO: Healtcheck prevents the container from starting with Docker
    ## MUST BE FIXED
    # healthcheck:
    #   test: ['CMD-SHELL', 'curl -f http://localhost:5050 || exit 1']
    #   timeout: 10s
    #   interval: 10s
    #   retries: 10
    volumes:
      - ./src/:/app/src
  mongodb:
    image: mongo:4.4
    volumes:
      - ./data:/data/db
  nginx:
    image: nginx:1.21.3
    depends_on:
      - front
      - back
    restart: always
    ports:
      - ${GATEWAY_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../2109-wns-paris-les-semicroustillant-front/src:/2109-wns-paris-les-semicroustillant-front/src
      - ./logs:/var/log/nginx
