version: '3.4'

services:
  front:
    build:
      context: ../2109-wns-paris-les-semicroustillant-front
      dockerfile: Dockerfile-dev
    ports:
      - 8080:3000
    depends_on:
      back:
        condition: service_healthy
    volumes:
      - ../2109-wns-paris-les-semicroustillant-front/src:/app/src
    healthcheck:
      test: curl -X GET http://localhost:3000 || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
  back:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    ports:
      - 5050:4000
    depends_on:
      - mongo-seed
    command: npm start
    volumes:
      - ./src/:/app/src
    healthcheck:
      test: curl -X GET http://localhost:4000/.well-known/apollo/server-health || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
  mongo-seed:
    build:
      context: ./
      dockerfile: DockerFile-dev-mongo-seed
    depends_on:
      mongodb:
        condition: service_healthy
  mongodb:
    container_name: mongo-database
    image: mongo
    ports:
      - 27018:27017
    volumes:
      - ./data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
