services:
  front:
    build: ../2109-wns-paris-les-semicroustillant-front
    ports:
      - 8080:3000
    # depends_on:
    #   back:
    #     condition: service_healthy
  back:
    build: ./
    ports:
      - 5050:4000
    # healthcheck:
    #   test: ['CMD-SHELL', 'curl -f http://localhost:5050 || exit 1']
    #   timeout: 10s
    #   interval: 10s
    #   retries: 10
  mongodb:
    image: mongo
    volumes:
      - ./data:/data/db
