name: Push docker image in staging

on:
  push:
    branches:
      - 'staging'

jobs:
  docker:
    name: Push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: Create a .env file
        run: |
          touch .env
          echo SECRET_JWT_KEY=${{ secrets.SECRET_JWT_KEY }} >> .env
          echo DB_NAME=${{ secrets.DB_NAME }} >> .env
          cat .env

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-staging
          push: true
          tags: semiwcs/2109-wns-paris-les-semicroustillant-back:latest
