name: Back Tests

on: pull_request

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-18.4
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run lint
        run: npm run lint

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    needs: ['lint']
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run unit-test

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    needs: ['lint']
    env:
      SECRET_JWT_KEY: ${{ secrets.SECRET_JWT_KEY }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run int-test
