name: Back Tests

on: pull_request

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      SECRET_JWT_KEY: ${{ secrets.SECRET_JWT_KEY }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run lint
        run: npm run lint

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    needs: ['lint']
    steps:
      - name: ECHO
        run: echo ${{ secrets.SECRET_JWT_KEY }}
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
