name: Back test workflow

on: pull_request

jobs:
  back-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run tests
        run: npm install && npx jest
